from enum import Enum
from typing import Callable

import numpy as np
import scipy as sp
from mpi4py import MPI

from impurityModel.ed.manybody_basis import Basis
from impurityModel.ed.ManyBodyUtils import ManyBodyOperator, ManyBodyState, inner
from impurityModel.ed.block_math import (
    block_normalize,
    block_add_scaled,
    block_apply,
    block_combine,
    block_inner,
    block_orthogonalize,
)


class Reort(Enum):
    """
    Reorthogonalization mode for the Lanczos algorithm.

    Attributes
    ----------
    NONE : int
        No reorthogonalization.
    PARTIAL : int
        Partial reorthogonalization.
    FULL : int
        Full reorthogonalization.
    PERIODIC : int
        Periodic reorthogonalization.
    """

    NONE = 0
    PARTIAL = 1
    FULL = 2
    PERIODIC = 3
    SELECTIVE = 4


def calculate_thermal_gs(h, block_size, e_max, v0=None, reort=Reort.FULL, comm=None):
    """
    Calculate the thermal ground states of a Hamiltonian using the block Lanczos algorithm.

    Finds the eigenvalues and eigenvectors of the Hamiltonian `h` that are within
    `e_max` of the lowest eigenvalue.

    Parameters
    ----------
    h : scipy.sparse.linalg.LinearOperator or ndarray
        The Hamiltonian operator.
    block_size : int
        The block size for the block Lanczos method.
    e_max : float
        Keep eigenvalues that lie within `e_max` of the lowest eigenvalue.
    v0 : ndarray, optional
        The initial block of starting vectors. If None, random complex vectors are generated.
    reort : Reort, optional
        Reorthogonalization strategy. Default is `Reort.FULL`.
    comm : mpi4py.MPI.Comm, optional
        MPI communicator for parallel computation. Default is None.

    Returns
    -------
    eigvals : ndarray
        Sorted eigenvalues within the energy range.
    eigvecs : ndarray
        Corresponding eigenvectors in the original basis.
    """
    mpi = comm is not None
    rank = comm.rank if mpi else 0
    size = comm.size if mpi else 1

    def converged(alphas, betas, *args, **kwargs):
        """
        Check convergence of the thermal ground states block Lanczos calculation.

        Parameters
        ----------
        alphas : ndarray
            The diagonal block matrices (alpha) generated by block Lanczos.
        betas : ndarray
            The off-diagonal block matrices (beta) generated by block Lanczos.
        *args : list
            Additional positional arguments.
        **kwargs : dict
            Additional keyword arguments.

        Returns
        -------
        converged : bool
            True if the thermal ground states have converged, False otherwise.
        """
        e, s = eigsh(alphas, betas, de=e_max, select="m")
        sorted_indices = np.argsort(e)
        e = e[sorted_indices]
        s = s[:, sorted_indices]
        mask = e - np.min(e) <= e_max
        return np.linalg.norm(betas[-1] @ s[-block_size:, mask], ord=2) < 1e-6

    if v0 is None:
        v0 = np.random.rand(h.shape[1], block_size) + 1j * np.random.rand(h.shape[1], block_size)
        if mpi:
            counts = np.empty((size), dtype=int)
            comm.Allgather(np.array([v0.size], dtype=int), counts)
            offsets = np.array([np.sum(counts[:r]) for r in range(size)], dtype=int)
            v0_full = np.empty((h.shape[0], block_size), dtype=complex, order="C") if rank == 0 else None
            comm.Gatherv(v0, (v0_full, counts, offsets, MPI.C_DOUBLE_COMPLEX), root=0)
            if rank == 0:
                v0_full, _ = sp.linalg.qr(v0_full, mode="economic", overwrite_a=True, check_finite=False)
            comm.Scatterv((v0_full, counts, offsets, MPI.C_DOUBLE_COMPLEX), v0, root=0)
        else:
            v0, _ = sp.linalg.qr(v0, mode="economic", overwrite_a=True, check_finite=False)
    elif v0.shape[1] < block_size:
        new_v0 = np.random.rand(v0.shape[0], block_size - v0.shape[1]) + 1j * np.random.rand(
            v0.shape[0], block_size - v0.shape[1]
        )
        new_v0 -= v0 @ np.conj(v0.T) @ new_v0
        new_v0, _ = sp.linalg.qr(new_v0, mode="economic", overwrite_a=True, check_finite=False)
        v0 = np.append(v0, new_v0, axis=1)
    elif v0.shape[1] > block_size:
        v0 = v0[:, :block_size]
    alphas, betas, Q = get_block_Lanczos_matrices(
        psi0=v0,
        h=h,
        converged=converged,
        verbose=True,
        reort_mode=reort,
        comm=comm,
    )
    if rank == 0:
        eigvals, eigvecs = eigsh(alphas, betas, de=e_max, Q=Q[:, : alphas.shape[0] * alphas.shape[1]], select="m")
    else:
        eigvals = None
        eigvecs = None
    if mpi:
        eigvals = comm.bcast(eigvals, root=0)
        eigvecs = comm.bcast(eigvecs, root=0)
    return eigvals, eigvecs


def build_banded_matrix(alphas, betas):
    """
    Build a banded matrix representation from diagonal and off-diagonal Lanczos blocks.

    Constructs a banded matrix format suitable for `scipy.linalg.eig_banded`.

    Parameters
    ----------
    alphas : ndarray
        Diagonal block matrices (alpha) of shape `(k, p, p)`.
    betas : ndarray
        Off-diagonal block matrices (beta) of shape `(k, p, p)`.

    Returns
    -------
    bands : ndarray
        Banded matrix representation in lower diagonal form.
        Shape is `(p + 1, k * p)`.
    """
    k = alphas.shape[0]
    p = alphas.shape[1]
    bands = np.zeros((p + 1, k * p), dtype=alphas.dtype)
    bands[0, :] = np.diagonal(alphas, offset=0, axis1=1, axis2=2).flatten()
    for i in range(1, p + 1):
        alpha_diags = np.diagonal(alphas, offset=-i, axis1=1, axis2=2)
        beta_diags = np.diagonal(betas, offset=p - i, axis1=1, axis2=2)
        bands[i, :] = np.concatenate([alpha_diags, beta_diags], axis=1).flatten()
    return bands


def _build_full_T(alphas, betas, comm=None):
    m = len(alphas)
    mpi = comm is not None
    if m == 0:
        return np.zeros((0, 0), dtype=complex)
    n = alphas[0].shape[0]
    T = np.zeros((m * n, m * n), dtype=complex)
    for i in range(m):
        T[i * n : (i + 1) * n, i * n : (i + 1) * n] = alphas[i]
        if i < m - 1:
            T[i * n : (i + 1) * n, (i + 1) * n : (i + 2) * n] = betas[i].conj().T
            T[(i + 1) * n : (i + 2) * n, i * n : (i + 1) * n] = betas[i]

    return T


def _extract_blocks(T, m, n):
    alphas = np.zeros((m, n, n), dtype=complex)
    betas = np.zeros((m - 1, n, n), dtype=complex)
    for i in range(m):
        alphas[i] = T[i * n : (i + 1) * n, i * n : (i + 1) * n]
        if i < m - 1:
            betas[i] = T[(i + 1) * n : (i + 2) * n, i * n : (i + 1) * n]
    return alphas, betas


def eigsh(alphas, betas, de=None, Q=None, eigvals_only=False, select="a", select_range=None, max_ev=0, comm=None):
    """
    Solve the (block) lanczos eigenvalue problem. Return the eigenvalues and
    (optionally) the corresponding eigenvectors. Return only eigenvalues (and,
    optionally eigenvectors) lying within de of the lowest eigenvalue.
    NOTE: len(alphas) == len(betas) == n, however the last element in betas
    will not be accessed.
         [alpha_0  beta_0* 0        ...      ]
    Tm = [beta_0   alpha_1 beta_1*  ...      ]
         [0        beta_1  ...      beta_n-2*]
         [...              beta_n-2 alpha_n-1  ]
    If eigvals_only is True, only return the eigenvalues.
    If Q is None, return the eigenvectors in the Krylov basis. Otherwise, the
    eigenvectors are transformed using Q, as such: eigvecs = Q @ eigvecs, and
    then returned.
    Parameters
    ==========
    alphas - (block) diagonal terms of the Matrix in the Krylov basis. [alpha_0
             ,alpha_1, ..., alpha_n]
    betas - (block) off-diagnal terms of the Matrix in the Krylov basis.[beta_0
            ,beta_1, ..., beta_n]
    """
    within_gs = False
    if select == "m":
        assert de is not None
        select = "a"
        within_gs = True

    Tm = build_banded_matrix(alphas, betas)
    if eigvals_only:
        eigvals = sp.linalg.eig_banded(
            Tm,
            lower=True,
            eigvals_only=True,
            overwrite_a_band=True,
            check_finite=False,
            select=select,
            select_range=select_range,
            max_ev=max_ev,
        )
        eigvals = np.sort(eigvals)
        if within_gs:
            return eigvals[eigvals - eigvals[0] <= de]
        return eigvals

    eigvals, eigvecs = sp.linalg.eig_banded(
        Tm,
        lower=True,
        eigvals_only=False,
        overwrite_a_band=True,
        check_finite=False,
        select=select,
        select_range=select_range,
        max_ev=max_ev,
    )
    if within_gs:
        mask = eigvals - np.min(eigvals) <= de
    else:
        mask = np.ones(len(eigvals), dtype=bool)

    mask_indices = np.where(mask)[0]
    sort_indices = np.argsort(eigvals[mask_indices])
    final_indices = mask_indices[sort_indices]

    eigvals = eigvals[final_indices]
    eigvecs = eigvecs[:, final_indices]

    if Q is not None:
        eigvecs = Q @ eigvecs

    return eigvals, eigvecs


def block_lanczos_array(
    psi0: np.ndarray,
    h_op,
    converged: Callable[[np.ndarray, np.ndarray], bool],
    verbose: bool = False,
    reort: Reort = Reort.NONE,
    alphas: np.ndarray = None,
    betas: np.ndarray = None,
    Q: np.ndarray = None,
    W: np.ndarray = None,
    return_W: bool = False,
    **kwargs,
):
    """
    Perform block Lanczos algorithm using dense numpy arrays for vectors.
    """
    from impurityModel.ed.BlockLanczosArray import block_lanczos_array_cy

    return block_lanczos_array_cy(psi0, h_op, converged, verbose, reort, alphas, betas, Q, W, return_W, **kwargs)
