from enum import Enum
from typing import Callable

import numpy as np
import scipy as sp
from mpi4py import MPI

from impurityModel.ed.manybody_basis import Basis
from impurityModel.ed.ManyBodyUtils import ManyBodyOperator, ManyBodyState, inner


class Reort(Enum):
    """
    Reorthogonalization mode for the Lanczos algorithm.

    Attributes
    ----------
    NONE : int
        No reorthogonalization.
    PARTIAL : int
        Partial reorthogonalization.
    FULL : int
        Full reorthogonalization.
    PERIODIC : int
        Periodic reorthogonalization.
    """

    NONE = 0
    PARTIAL = 1
    FULL = 2
    PERIODIC = 3
    SELECTIVE = 4


def calculate_thermal_gs(h, block_size, e_max, v0=None, reort=Reort.FULL, comm=None):
    """
    Calculate the thermal ground states of a Hamiltonian using the block Lanczos algorithm.

    Finds the eigenvalues and eigenvectors of the Hamiltonian `h` that are within
    `e_max` of the lowest eigenvalue.

    Parameters
    ----------
    h : scipy.sparse.linalg.LinearOperator or ndarray
        The Hamiltonian operator.
    block_size : int
        The block size for the block Lanczos method.
    e_max : float
        Keep eigenvalues that lie within `e_max` of the lowest eigenvalue.
    v0 : ndarray, optional
        The initial block of starting vectors. If None, random complex vectors are generated.
    reort : Reort, optional
        Reorthogonalization strategy. Default is `Reort.FULL`.
    comm : mpi4py.MPI.Comm, optional
        MPI communicator for parallel computation. Default is None.

    Returns
    -------
    eigvals : ndarray
        Sorted eigenvalues within the energy range.
    eigvecs : ndarray
        Corresponding eigenvectors in the original basis.
    """
    mpi = comm is not None
    rank = comm.rank if mpi else 0
    size = comm.size if mpi else 1

    def converged(alphas, betas, *args, **kwargs):
        """
        Check convergence of the thermal ground states block Lanczos calculation.

        Parameters
        ----------
        alphas : ndarray
            The diagonal block matrices (alpha) generated by block Lanczos.
        betas : ndarray
            The off-diagonal block matrices (beta) generated by block Lanczos.
        *args : list
            Additional positional arguments.
        **kwargs : dict
            Additional keyword arguments.

        Returns
        -------
        converged : bool
            True if the thermal ground states have converged, False otherwise.
        """
        e, s = eigsh(alphas, betas, de=e_max, select="m")
        sorted_indices = np.argsort(e)
        e = e[sorted_indices]
        s = s[:, sorted_indices]
        mask = e - np.min(e) <= e_max
        return np.linalg.norm(betas[-1] @ s[-block_size:, mask], ord=2) < 1e-6

    if v0 is None:
        v0 = np.random.rand(h.shape[1], block_size) + 1j * np.random.rand(h.shape[1], block_size)
        if mpi:
            counts = np.empty((size), dtype=int)
            comm.Allgather(np.array([v0.size], dtype=int), counts)
            offsets = np.array([np.sum(counts[:r]) for r in range(size)], dtype=int)
            v0_full = np.empty((h.shape[0], block_size), dtype=complex, order="C") if rank == 0 else None
            comm.Gatherv(v0, (v0_full, counts, offsets, MPI.C_DOUBLE_COMPLEX), root=0)
            if rank == 0:
                v0_full, _ = sp.linalg.qr(v0_full, mode="economic", overwrite_a=True, check_finite=False)
            comm.Scatterv((v0_full, counts, offsets, MPI.C_DOUBLE_COMPLEX), v0, root=0)
        else:
            v0, _ = sp.linalg.qr(v0, mode="economic", overwrite_a=True, check_finite=False)
    elif v0.shape[1] < block_size:
        new_v0 = np.random.rand(v0.shape[0], block_size - v0.shape[1]) + 1j * np.random.rand(
            v0.shape[0], block_size - v0.shape[1]
        )
        new_v0 -= v0 @ np.conj(v0.T) @ new_v0
        new_v0, _ = sp.linalg.qr(new_v0, mode="economic", overwrite_a=True, check_finite=False)
        v0 = np.append(v0, new_v0, axis=1)
    elif v0.shape[1] > block_size:
        v0 = v0[:, :block_size]
    alphas, betas, Q = get_block_Lanczos_matrices(
        psi0=v0,
        h=h,
        converged=converged,
        verbose=True,
        reort_mode=reort,
        comm=comm,
    )
    if rank == 0:
        eigvals, eigvecs = eigsh(alphas, betas, de=e_max, Q=Q[:, : alphas.shape[0] * alphas.shape[1]], select="m")
    else:
        eigvals = None
        eigvecs = None
    if mpi:
        eigvals = comm.bcast(eigvals, root=0)
        eigvecs = comm.bcast(eigvecs, root=0)
    return eigvals, eigvecs


def build_banded_matrix(alphas, betas):
    """
    Build a banded matrix representation from diagonal and off-diagonal Lanczos blocks.

    Constructs a banded matrix format suitable for `scipy.linalg.eig_banded`.

    Parameters
    ----------
    alphas : ndarray
        Diagonal block matrices (alpha) of shape `(k, p, p)`.
    betas : ndarray
        Off-diagonal block matrices (beta) of shape `(k, p, p)`.

    Returns
    -------
    bands : ndarray
        Banded matrix representation in lower diagonal form.
        Shape is `(p + 1, k * p)`.
    """
    k = alphas.shape[0]
    p = alphas.shape[1]
    bands = np.zeros((p + 1, k * p), dtype=alphas.dtype)
    bands[0, :] = np.diagonal(alphas, offset=0, axis1=1, axis2=2).flatten()
    for i in range(1, p + 1):
        alpha_diags = np.diagonal(alphas, offset=-i, axis1=1, axis2=2)
        beta_diags = np.diagonal(betas, offset=p - i, axis1=1, axis2=2)
        bands[i, :] = np.concatenate([alpha_diags, beta_diags], axis=1).flatten()
    return bands


def _build_full_T(alphas, betas):
    m = len(alphas)
    if m == 0:
        return np.zeros((0, 0), dtype=complex)
    n = alphas[0].shape[0]
    T = np.zeros((m * n, m * n), dtype=complex)
    for i in range(m):
        T[i * n : (i + 1) * n, i * n : (i + 1) * n] = alphas[i]
        if i < m - 1 and i < len(betas):
            T[(i + 1) * n : (i + 2) * n, i * n : (i + 1) * n] = betas[i]
            T[i * n : (i + 1) * n, (i + 1) * n : (i + 2) * n] = np.conj(betas[i].T)
    return T


def _extract_blocks(T, m, n):
    alphas = np.zeros((m, n, n), dtype=complex)
    betas = np.zeros((m - 1, n, n), dtype=complex)
    for i in range(m):
        alphas[i] = T[i * n : (i + 1) * n, i * n : (i + 1) * n]
        if i < m - 1:
            betas[i] = T[(i + 1) * n : (i + 2) * n, i * n : (i + 1) * n]
    return alphas, betas


def eigsh(alphas, betas, de=None, Q=None, eigvals_only=False, select="a", select_range=None, max_ev=0, comm=None):
    """
    Solve the (block) lanczos eigenvalue problem. Return the eigenvalues and
    (optionally) the corresponding eigenvectors. Return only eigenvalues (and,
    optionally eigenvectors) lying within de of the lowest eigenvalue.
    NOTE: len(alphas) == len(betas) == n, however the last element in betas
    will not be accessed.
         [alpha_0  beta_0* 0        ...      ]
    Tm = [beta_0   alpha_1 beta_1*  ...      ]
         [0        beta_1  ...      beta_n-2*]
         [...              beta_n-2 alpha_n-1  ]
    If eigvals_only is True, only return the eigenvalues.
    If Q is None, return the eigenvectors in the Krylov basis. Otherwise, the
    eigenvectors are transformed using Q, as such: eigvecs = Q @ eigvecs, and
    then returned.
    Parameters
    ==========
    alphas - (block) diagonal terms of the Matrix in the Krylov basis. [alpha_0
             ,alpha_1, ..., alpha_n]
    betas - (block) off-diagnal terms of the Matrix in the Krylov basis.[beta_0
            ,beta_1, ..., beta_n]
    """
    within_gs = False
    if select == "m":
        assert de is not None
        select = "a"
        within_gs = True

    Tm = build_banded_matrix(alphas, betas)
    if eigvals_only:
        eigvals = sp.linalg.eig_banded(
            Tm,
            lower=True,
            eigvals_only=True,
            overwrite_a_band=True,
            check_finite=False,
            select=select,
            select_range=select_range,
            max_ev=max_ev,
        )
        eigvals = np.sort(eigvals)
        if within_gs:
            return eigvals[eigvals - eigvals[0] <= de]
        return eigvals

    eigvals, eigvecs = sp.linalg.eig_banded(
        Tm,
        lower=True,
        eigvals_only=False,
        overwrite_a_band=True,
        check_finite=False,
        select=select,
        select_range=select_range,
        max_ev=max_ev,
    )
    if within_gs:
        mask = eigvals - np.min(eigvals) <= de
    else:
        mask = np.ones(len(eigvals), dtype=bool)

    mask_indices = np.where(mask)[0]
    sort_indices = np.argsort(eigvals[mask_indices])
    final_indices = mask_indices[sort_indices]

    eigvals = eigvals[final_indices]
    eigvecs = eigvecs[:, final_indices]

    if Q is not None:
        eigvecs = Q @ eigvecs

    return eigvals, eigvecs


def estimate_orthonormality(W, alphas, betas, eps=np.finfo(float).eps, N=1, rng=np.random.default_rng()):
    """Estimate the overlap between obtained Lanczos vectors at a ceratin iteration.
    W, alphas and betas contain all the required information for estimating the overlap.
    The stats dictionary contains the following keys:
    * w_bar  - The absolute values of the estimated overlaps for the second row
               of W.
    Parameters:
    W      - Array containing the two latest etimates of overlap. Dimensions (2, i+1, n, n)
    alphas - Array containing the (block) diagonal elements obtained from the
             (block) Lanczos method. Dimensions (i+1, n, n)
    betas  - Array containing the (block) off diagonal elements obtained from the
             (block) Lanczos method. Dimensions (i+1, n, n)
    eps    - Precision of orthogonality. Default: machine precision
    A_norm - Estimate of the norm of the matrix A. Default: 1
    Returns:
    W_out  - Estimated overlaps of the last two vectors obtained from the (block)
             Lanczos method. Dimensions (2, i+1, n, n)
    """
    # i is the index of the latest calculated vector
    i = alphas.shape[0] - 1
    n = alphas.shape[1]

    is_full = W.shape[0] == i + 1

    W_out = np.zeros((i + 2 if is_full else 2, i + 2, n, n), dtype=complex)
    w_bar = np.zeros((i + 2, n, n), dtype=complex)
    w_bar[i + 1, :, :] = np.identity(n)
    w_bar[i, :, :] = (
        eps * N * sp.linalg.solve_triangular(betas[i], betas[0], lower=False, trans="C", check_finite=False)
    )

    W_prev = W[-1]
    W_prev_prev = W[-2] if i > 0 else W[-1]

    if i == 0:
        if is_full:
            W_out[:1, : i + 1] = W
        else:
            W_out[0, : i + 1] = W[1]
        W_out[-1, : i + 2] = w_bar
        return W_out

    w_bar[0] = W_prev[1] @ betas[0] + W_prev[0] @ alphas[0] - alphas[i] @ W_prev[0] - betas[i - 1] @ W_prev_prev[0]
    w_bar[0] = sp.linalg.solve_triangular(betas[i], w_bar[0], lower=False, trans="C", check_finite=False)
    w_bar[1:i] = (
        W_prev[2 : i + 1] @ betas[1:i]
        + W_prev[1:i] @ alphas[1:i]
        - alphas[i][np.newaxis, :, :] @ W_prev[1:i]
        + W_prev[: i - 1] @ np.conj(np.transpose(betas[: i - 1], axes=[0, 2, 1]))
        - betas[i - 1][np.newaxis, :, :] @ W_prev_prev[1:i]
    )
    w_bar[1:i] = np.linalg.solve(np.conj(betas[i].T)[np.newaxis, :, :], w_bar[1:i])

    w_bar[:i] += eps * (betas[i] + betas[:i])

    if is_full:
        W_out[:-1, : i + 1] = W
    else:
        W_out[0, : i + 1] = W[1]
    W_out[-1, : i + 2] = w_bar

    return W_out


def _reorthogonalize_dense(wp, basis_vectors, indices=None):
    """
    Project `wp` against a subset of `basis_vectors` using classical Gram-Schmidt.
    """
    if indices is None:
        indices = range(len(basis_vectors))
    for _ in range(2):
        for j in indices:
            overlap = np.conj(basis_vectors[j].T) @ wp
            wp -= basis_vectors[j] @ overlap


def _reorthogonalize_sparse(wp, Q_states, indices, inner_func, mpi, comm, n):
    """
    Project `wp` against a subset of `Q_states` using classical Gram-Schmidt in sparse format.
    """
    if indices is None:
        indices = range(len(Q_states))
    if not indices:
        return

    Q_sub = [Q_states[i] for i in indices] if len(indices) < len(Q_states) else Q_states

    from impurityModel.ed.ManyBodyUtils import add_scaled_multi, inner_multi

    for _ in range(2):
        overlaps = inner_multi(Q_sub, wp)
        if mpi:
            comm.Allreduce(MPI.IN_PLACE, overlaps, op=MPI.SUM)
        add_scaled_multi(wp, Q_sub, -overlaps)


def get_block_Lanczos_matrices_dense(
    psi0: np.ndarray,
    h,
    converged: Callable[[np.ndarray, np.ndarray], bool],
    verbose: bool = True,
    reort_mode=Reort.NONE,
    **kwargs,
):
    """
    Compute block Lanczos matrices for a dense Hamiltonian matrix.

    Parameters
    ----------
    psi0 : ndarray
        The initial starting block of vectors. Shape: `(N, n)`.
    h : ndarray
        Dense Hamiltonian matrix. Shape: `(N, N)`.
    converged : callable
        Function `converged(alphas, betas, verbose=verbose)` returning True if converged.
    verbose : bool, optional
        Verbosity flag. Default is True.
    reort_mode : Reort, optional
        Reorthogonalization strategy. Default is `Reort.NONE`.
    **kwargs : dict
        Additional keyword arguments. `reort_period` can be provided for PERIODIC mode.

    Returns
    -------
    alphas : ndarray
        The diagonal block matrices (alpha) generated by block Lanczos.
    betas : ndarray
        The off-diagonal block matrices (beta) generated by block Lanczos.
    """
    krylovSize = h.shape[0]

    N = h.shape[0]
    n = psi0.shape[1] if len(psi0.shape) == 2 else 1

    q = np.zeros((2, N, n), dtype=complex, order="C")
    wp = np.empty((N, n), dtype=complex, order="C")
    q[1] = psi0
    Q_list = [q[1].copy()]

    it_max = int(np.ceil(krylovSize / n))
    alphas = np.empty((it_max, n, n), dtype=complex)
    betas = np.empty((it_max, n, n), dtype=complex)

    W = None
    reort_eps = np.sqrt(np.finfo(float).eps)
    period = kwargs.get("reort_period", 5)

    # Run at least 1 iteration (to generate $\alpha_0$).
    # We can also not generate more than N Lanczos vectors, meaning we can
    # take at most N/n steps in total
    for i in range(it_max):
        wp = h @ q[1]

        alphas[i] = np.conj(q[1].T) @ wp
        if i == 0:
            wp = wp - q[1] @ alphas[i]
        else:
            wp -= q[1] @ alphas[i] + q[0] @ np.conj(betas[i - 1].T)

        if reort_mode == Reort.FULL or (reort_mode == Reort.PERIODIC and i > 0 and i % period == 0):
            _reorthogonalize_dense(wp, Q_list)

        q[0] = q[1].copy()
        q[1], betas[i] = sp.linalg.qr(wp, mode="economic", overwrite_a=False, check_finite=False)

        if reort_mode in (Reort.PARTIAL, Reort.SELECTIVE):
            if W is None:
                W = np.zeros((2, 1, n, n), dtype=complex)
                W[1, 0] = np.eye(n)
            W = estimate_orthonormality(W, alphas[: i + 1], betas[: i + 1], eps=np.finfo(float).eps)
            if i > 0 and np.max(np.abs(W[1, : i + 1])) > reort_eps:
                bad_indices = [j for j in range(len(Q_list)) if np.max(np.abs(W[1, j])) > reort_eps * 1e-2]
                bad_indices_prev = [j for j in bad_indices if j < len(Q_list) - 1]
                if reort_mode == Reort.PARTIAL:
                    _reorthogonalize_dense(Q_list[-1], Q_list[:-1], bad_indices_prev)
                    _reorthogonalize_dense(wp, Q_list, bad_indices)
                elif reort_mode == Reort.SELECTIVE:
                    eigvals, eigvecs = eigsh(alphas[: i + 1], betas[: i + 1], select="a", max_ev=0)
                    error_bounds = np.linalg.norm(betas[i], ord=2) * np.abs(eigvecs[-n:, :]).max(axis=0)
                    converged_mask = error_bounds < reort_eps
                    if np.any(converged_mask):
                        converged_Ritz = [np.concatenate(Q_list, axis=1) @ eigvecs[:, converged_mask]]
                        _reorthogonalize_dense(Q_list[-1], converged_Ritz)
                        _reorthogonalize_dense(wp, converged_Ritz)
                    _reorthogonalize_dense(Q_list[-1], Q_list[:-1], bad_indices_prev)
                    _reorthogonalize_dense(wp, Q_list, bad_indices)
                q[1] = Q_list[-1].copy()

                q[1], betas[i] = sp.linalg.qr(wp, mode="economic", overwrite_a=False, check_finite=False)
                W[1, bad_indices] = np.finfo(float).eps * np.eye(n)
                W[0, bad_indices_prev] = np.finfo(float).eps * np.eye(n)

        q[1] = np.ascontiguousarray(q[1])
        Q_list.append(q[1].copy())

        if converged(alphas[: i + 1], betas[: i + 1], verbose=verbose):
            break

    return alphas[: i + 1], betas[: i + 1]


def get_block_Lanczos_matrices(
    psi0: np.ndarray,
    h,
    converged: Callable[[np.ndarray, np.ndarray], bool],
    verbose: bool = True,
    comm=None,
    reort_mode=Reort.NONE,
    build_krylov_basis=True,
    **kwargs,
):
    """
    Compute block Lanczos matrices for a general Hamiltonian operator.

    Parameters
    ----------
    psi0 : ndarray
        Initial starting block of vectors. Shape: `(local_basis_size, n)`.
    h : scipy.sparse.linalg.LinearOperator or ndarray
        Hamiltonian operator.
    converged : callable
        Convergence check function taking `alphas` and `betas` and returning boolean.
    verbose : bool, optional
        If True, output progress. Default is True.
    comm : mpi4py.MPI.Comm, optional
        MPI communicator. Default is None.
    reort_mode : Reort, optional
        Reorthogonalization strategy. Default is `Reort.NONE`.
    build_krylov_basis : bool, optional
        Whether to build and return the full Krylov basis matrix `Q`. Default is True.
    **kwargs : dict
        Additional keyword arguments.

    Returns
    -------
    alphas : ndarray
        Diagonal block matrices (alpha).
    betas : ndarray
        Off-diagonal block matrices (beta).
    Q : ndarray or None
        Krylov basis vectors matrix if `build_krylov_basis` is True, else None.
    """
    mpi = comm is not None
    rank = comm.rank if mpi else 0
    krylovSize = h.shape[0]
    if mpi:
        counts = np.empty((comm.size), dtype=int)
        comm.Allgather(np.array([psi0.size], dtype=int), counts)
        offsets = np.array([np.sum(counts[:r]) for r in range(comm.size)], dtype=int)

    N = h.shape[0]
    n = psi0.shape[1] if len(psi0.shape) == 2 else 1
    it_max = int(np.ceil(krylovSize / n))

    if rank == 0:
        q = np.zeros((2, N, n), dtype=complex, order="C")
        wp = np.empty((N, n), dtype=complex, order="C")
        alphas = np.empty((it_max, n, n), dtype=complex, order="C")
        betas = np.empty((it_max, n, n), dtype=complex, order="C")
    else:
        q = np.empty((2, 0, 0))
        wp = None
    if mpi:
        comm.Gatherv(psi0, (q[1] if rank == 0 else None, counts, offsets, MPI.C_DOUBLE_COMPLEX), root=0)
        if rank == 0:
            Q_list = [q[1].copy()]
    else:
        q[1] = psi0.copy()
        Q_list = [q[1].copy()]
    qi = np.ascontiguousarray(psi0).copy()

    done = False

    W = None
    reort_eps = np.sqrt(np.finfo(float).eps)
    period = kwargs.get("reort_period", 5)

    # Run at least 1 iteration (to generate $\alpha_0$).
    # We can also not generate more than N Lanczos vectors, meaning we can
    # take at most N/n steps in total
    for i in range(it_max):
        wp = h @ qi
        if mpi and not isinstance(h, sp.sparse.linalg.LinearOperator):
            comm.Reduce(MPI.IN_PLACE if rank == 0 else wp, wp, op=MPI.SUM, root=0)

        if rank == 0:
            alphas[i] = np.conj(q[1].T) @ wp
            if i == 0:
                wp -= q[1] @ alphas[i]
            else:
                wp -= q[1] @ alphas[i] + q[0] @ np.conj(betas[i - 1].T)

            if reort_mode == Reort.FULL or (reort_mode == Reort.PERIODIC and i > 0 and i % period == 0):
                if not build_krylov_basis:
                    raise RuntimeError("Krylov basis must be built for reorthogonalization")
                _reorthogonalize_dense(wp, Q_list)

            q[0] = q[1].copy()
            q[1], betas[i] = sp.linalg.qr(wp, mode="economic", overwrite_a=False, check_finite=False)

            if reort_mode in (Reort.PARTIAL, Reort.SELECTIVE):
                if not build_krylov_basis:
                    raise RuntimeError("Krylov basis must be built for reorthogonalization")
                if W is None:
                    W = np.zeros((2, 1, n, n), dtype=complex)
                    W[1, 0] = np.eye(n)
                W = estimate_orthonormality(W, alphas[: i + 1], betas[: i + 1], eps=np.finfo(float).eps)
                if i > 0 and np.max(np.abs(W[1, : i + 1])) > reort_eps:
                    bad_indices = [j for j in range(len(Q_list)) if np.max(np.abs(W[1, j])) > reort_eps * 1e-2]
                    bad_indices_prev = [j for j in bad_indices if j < len(Q_list) - 1]
                    if reort_mode == Reort.PARTIAL:
                        _reorthogonalize_dense(Q_list[-1], Q_list[:-1], bad_indices_prev)
                        _reorthogonalize_dense(wp, Q_list, bad_indices)
                    elif reort_mode == Reort.SELECTIVE:
                        eigvals, eigvecs = eigsh(alphas[: i + 1], betas[: i + 1], select="a", max_ev=0)
                        error_bounds = np.linalg.norm(betas[i], ord=2) * np.abs(eigvecs[-n:, :]).max(axis=0)
                        converged_mask = error_bounds < reort_eps
                        if np.any(converged_mask):
                            converged_Ritz = [np.concatenate(Q_list, axis=1) @ eigvecs[:, converged_mask]]
                            _reorthogonalize_dense(Q_list[-1], converged_Ritz)
                            _reorthogonalize_dense(wp, converged_Ritz)
                        _reorthogonalize_dense(Q_list[-1], Q_list[:-1], bad_indices_prev)
                        _reorthogonalize_dense(wp, Q_list, bad_indices)

                    q[1], betas[i] = sp.linalg.qr(wp, mode="economic", overwrite_a=False, check_finite=False)
                    W[1, bad_indices] = np.finfo(float).eps * np.eye(n)
                    W[0, bad_indices_prev] = np.finfo(float).eps * np.eye(n)

            q[1] = np.ascontiguousarray(q[1])
            Q_list.append(q[1].copy())
            if mpi:
                qi[:] = q[1, : counts[0] // n]
            else:
                qi[:] = q[1]

            done = converged(alphas[: i + 1], betas[: i + 1], verbose=verbose)

        if mpi:
            done = comm.bcast(done, root=0)
            comm.Scatterv(
                (q[1], counts, offsets, MPI.C_DOUBLE_COMPLEX),
                qi,
                root=0,
            )

        else:
            qi = q[1].copy()
        if done:
            break

    if rank == 0:
        alphas = alphas[: i + 1]
        betas = betas[: i + 1]
        Q = np.concatenate(Q_list[: i + 1], axis=1) if build_krylov_basis else None
    else:
        Q = None
    # Distribute Lanczos matrices to all ranks
    if mpi:
        if rank != 0:
            alphas = np.empty((i + 1, n, n), dtype=complex, order="C")
            betas = np.empty((i + 1, n, n), dtype=complex, order="C")
        comm.Bcast(alphas, root=0)
        comm.Bcast(betas, root=0)

    return alphas, betas, Q


from impurityModel.ed.ManyBodyUtils import add_scaled_multi, inner_multi


def block_lanczos_array(
    psi0: np.ndarray,
    h_op,
    converged: Callable[[np.ndarray, np.ndarray], bool],
    verbose: bool = False,
    reort: Reort = Reort.NONE,
    alphas: np.ndarray = None,
    betas: np.ndarray = None,
    Q: np.ndarray = None,
    W: np.ndarray = None,
    track_full_W: bool = False,
    return_W: bool = False,
    **kwargs,
):
    """
    Perform block Lanczos algorithm using dense numpy arrays for vectors.
    """
    build_krylov_basis = reort != Reort.NONE or True
    N = psi0.shape[0] if psi0 is not None else Q.shape[0]
    n = (psi0.shape[1] if len(psi0.shape) == 2 else 1) if psi0 is not None else alphas[0].shape[0]

    if alphas is not None and betas is not None and Q is not None:
        start_it = len(alphas)
        alphas_arr = alphas
        betas_arr = betas

        q0_fallback = psi0.copy() if psi0 is not None else Q[:, :n]
        q = [Q[:, (start_it - 1) * n : start_it * n] if start_it > 0 else q0_fallback]
        q.append(Q[:, start_it * n : (start_it + 1) * n] if start_it > 0 else q0_fallback)

        Q_list = [Q]
    else:
        start_it = 0
        alphas_arr = np.empty((0, n, n), dtype=complex)
        betas_arr = np.empty((0, n, n), dtype=complex)

        q = [np.zeros((N, n), dtype=complex)]
        q.append(psi0.copy() if len(psi0.shape) == 2 else psi0.reshape(-1, 1).copy())

        Q_list = [q[1].copy()] if build_krylov_basis else None

    alphas = alphas_arr
    betas = betas_arr

    it = start_it
    reort_eps = np.sqrt(np.finfo(float).eps)
    period = kwargs.get("reort_period", 5)
    max_iter = kwargs.get("max_iter", np.inf)

    def matmat(v):
        if hasattr(h_op, "dot"):
            return np.asarray(h_op.dot(v), dtype=complex)
        elif hasattr(h_op, "__matmul__"):
            return np.asarray(h_op @ v, dtype=complex)
        else:
            return np.asarray(h_op(v), dtype=complex)

    while it < max_iter:
        wp = matmat(q[1])

        alpha_i = q[1].conj().T @ wp
        alphas = np.append(alphas, [alpha_i], axis=0)
        betas = np.append(betas, np.zeros((1, n, n), dtype=complex), axis=0)

        wp -= q[1] @ alpha_i

        if it > 0:
            beta_prev_dag = np.conj(betas[it - 1].T)
            wp -= q[0] @ beta_prev_dag

        if reort == Reort.FULL or (reort == Reort.PERIODIC and it > 0 and it % period == 0):
            if not build_krylov_basis:
                raise RuntimeError("Krylov basis must be built for reorthogonalization")
            # Full reorthogonalization
            overlap = Q_list[0].conj().T @ wp
            wp -= Q_list[0] @ overlap

        M = wp.conj().T @ wp

        if np.any(np.isnan(M)) or np.any(np.isinf(M)):
            alphas = alphas[:-1]
            betas = betas[:-1]
            if build_krylov_basis:
                Q_list[0] = Q_list[0][:, :-n]
            break

        if np.linalg.cond(M) > 1 / (100 * np.finfo(float).eps):
            break

        try:
            L = sp.linalg.cholesky(M, lower=True)
        except sp.linalg.LinAlgError:
            break

        beta_i = np.conj(L.T)
        betas[it] = beta_i

        if reort in (Reort.PARTIAL, Reort.SELECTIVE):
            if not build_krylov_basis:
                raise RuntimeError("Krylov basis must be built for reorthogonalization")
            if W is None:
                if track_full_W:
                    W = np.zeros((1, 1, n, n), dtype=complex)
                    W[0, 0] = np.eye(n)
                else:
                    W = np.zeros((2, 1, n, n), dtype=complex)
                    W[1, 0] = np.eye(n)
            elif W.shape[0] < it + 1 or W.shape[1] < it + 1:
                if track_full_W:
                    W_new = np.zeros((it + 1, it + 1, n, n), dtype=complex)
                    W_new[: W.shape[0], : W.shape[1]] = W
                    W = W_new
                else:
                    W_new = np.zeros((2, it + 1, n, n), dtype=complex)
                    W_new[:, : W.shape[1]] = W
                    W = W_new

            W = estimate_orthonormality(W, alphas[: it + 1], betas[: it + 1], eps=np.finfo(float).eps)
            if it > 0 and np.max(np.abs(W[-1, : it + 1])) > reort_eps:
                bad_block_indices = [j for j in range(it + 1) if np.max(np.abs(W[-1, j])) > reort_eps * 1e-2]

                if reort == Reort.PARTIAL:
                    wp -= Q_list[0][:, : len(Q_list[0][0]) - n] @ (Q_list[0][:, : len(Q_list[0][0]) - n].conj().T @ wp)
                elif reort == Reort.SELECTIVE:
                    from impurityModel.ed.lanczos import eigsh

                    eigvals, eigvecs = eigsh(alphas[: it + 1], betas[: it + 1], select="a", max_ev=0)
                    error_bounds = np.linalg.norm(betas[it], ord=2) * np.abs(eigvecs[-n:, :]).max(axis=0)
                    converged_mask = error_bounds < reort_eps
                    if np.any(converged_mask):
                        converged_Ritz = Q_list[0] @ eigvecs[:, converged_mask]
                        Q_list[0][:, -n:] -= converged_Ritz @ (converged_Ritz.conj().T @ Q_list[0][:, -n:])
                        wp -= converged_Ritz @ (converged_Ritz.conj().T @ wp)
                    Q_list[0][:, -n:] -= Q_list[0][:, :-n] @ (Q_list[0][:, :-n].conj().T @ Q_list[0][:, -n:])
                    wp -= Q_list[0] @ (Q_list[0].conj().T @ wp)

                q[1][:] = Q_list[0][:, -n:]

                M = wp.conj().T @ wp
                if np.any(np.isnan(M)) or np.any(np.isinf(M)):
                    alphas = alphas[:-1]
                    betas = betas[:-1]
                    if build_krylov_basis:
                        Q_list[0] = Q_list[0][:, :-n]
                    break

                try:
                    if np.linalg.cond(M) > 1 / (100 * np.finfo(float).eps):
                        alphas = alphas[:-1]
                        betas = betas[:-1]
                        if build_krylov_basis:
                            Q_list[0] = Q_list[0][:, :-n]
                        break
                    L = sp.linalg.cholesky(M, lower=True)
                except sp.linalg.LinAlgError:
                    alphas = alphas[:-1]
                    betas = betas[:-1]
                    if build_krylov_basis:
                        Q_list[0] = Q_list[0][:, :-n]
                    break
                beta_i = np.conj(L.T)
                betas[it] = beta_i

                bad_block_indices_prev = [j for j in bad_block_indices if j < it]
                eps = np.finfo(float).eps
                W[-1, bad_block_indices] = eps * np.eye(n)
                if track_full_W:
                    W[-2, bad_block_indices_prev] = eps * np.eye(n)
                else:
                    W[0, bad_block_indices_prev] = eps * np.eye(n)

        import warnings

        try:
            with warnings.catch_warnings():
                warnings.simplefilter("error")
                beta_inv = sp.linalg.inv(beta_i)
        except Exception:
            break

        q_next = wp @ beta_inv

        if converged(alphas, betas, verbose=verbose):
            break

        q[0] = q[1]
        q[1] = q_next
        if build_krylov_basis:
            Q_list[0] = np.concatenate([Q_list[0], q_next], axis=1)
        it += 1

    if verbose:
        print(f"Coverged at iteration {it + 1}")

    res_Q = Q_list[0] if build_krylov_basis else None
    if return_W:
        return alphas, betas, res_Q, W
    return alphas, betas, res_Q


def block_lanczos_sparse(
    psi0: list[ManyBodyState],
    h_op: ManyBodyOperator,
    basis: Basis,
    converged: Callable[[np.ndarray, np.ndarray], bool],
    verbose: bool = False,
    reort: Reort = Reort.NONE,
    slaterWeightMin: float = 0,
    alphas: np.ndarray = None,
    betas: np.ndarray = None,
    Q: list[ManyBodyState] = None,
    W: np.ndarray = None,
    track_full_W: bool = False,
    return_W: bool = False,
    **kwargs,
):
    """
    Perform block Lanczos algorithm using sparse state representation.

    Parameters
    ----------
    psi0 : list of ManyBodyState
        Initial starting block of states.
    h_op : ManyBodyOperator
        Hamiltonian operator.
    basis : Basis
        The many-body basis which will be grown iteratively.
    converged : callable
        Convergence check function.
    verbose : bool, optional
        Verbosity flag. Default is False.
    reort : Reort, optional
        Reorthogonalization strategy. Default is `Reort.NONE`.
    slaterWeightMin : float, optional
        Slater determinant cutoff weight. Default is 0.
    alphas : ndarray, optional
        Precomputed alphas.
    betas : ndarray, optional
        Precomputed betas.
    Q : list, optional
        Precomputed Krylov basis states.
    W : ndarray, optional
        Precomputed orthonormalization estimates.
    track_full_W : bool, optional
        Whether to keep the full history of orthonormalization estimates.
    **kwargs : dict
        Additional keyword arguments.

    Returns
    -------
    alphas : ndarray
        Diagonal block matrices (alpha).
    betas : ndarray
        Off-diagonal block matrices (beta).
    Q : list of ManyBodyState or None
        Krylov basis states list if `reort != Reort.NONE`, else None.
    W : ndarray or None
        Orthonormalization estimates if tracked.
    """
    if not isinstance(h_op, ManyBodyOperator):
        h_op = ManyBodyOperator(h_op)
    if psi0 is not None:
        psi0 = [
            (
                ManyBodyState({basis.type.from_bytes(k) if isinstance(k, bytes) else k: v for k, v in psi.items()})
                if isinstance(psi, dict)
                else psi
            )
            for psi in psi0
        ]

    mpi = basis.comm is not None
    comm = basis.comm if mpi else MPI.COMM_SELF
    build_krylov_basis = reort != Reort.NONE or True

    # Initialize from passed state if provided
    if alphas is not None and betas is not None and Q is not None:
        start_it = len(alphas)
        n = alphas[0].shape[0]
        alphas_arr = alphas
        betas_arr = betas

        q0_fallback = psi0 if psi0 is not None else Q[:n]
        q = [[Q[i] for i in range((start_it - 1) * n, start_it * n)] if start_it > 0 else q0_fallback]
        q.append([Q[i] for i in range(start_it * n, (start_it + 1) * n)] if start_it > 0 else q0_fallback)

        Q_list = Q
    else:
        start_it = 0
        n = len(psi0)
        alphas_arr = np.empty((0, n, n), dtype=complex)
        betas_arr = np.empty((0, n, n), dtype=complex)

        q = [[ManyBodyState() for _ in range(n)]]

        if not isinstance(psi0[0], ManyBodyState):
            psi0_mbs = []
            for p in psi0:
                s = ManyBodyState()
                for k, v in p.items():
                    s[k] = v
                psi0_mbs.append(s)
            q.append(basis.redistribute_psis(psi0_mbs))
        else:
            q.append(basis.redistribute_psis(psi0))

        Q_list = [st.copy() for st in q[1]] if build_krylov_basis else None

    # Redefine references inside the loop
    alphas = alphas_arr
    betas = betas_arr
    Q = Q_list

    it = start_it

    reort_eps = np.sqrt(np.finfo(float).eps)
    period = kwargs.get("reort_period", 5)

    def matmat(v):
        """
        Apply the operator h_op to each state in block v and redistribute.
        """
        mv = h_op.apply_multi(v, cutoff=slaterWeightMin)
        return basis.redistribute_psis(mv)

    max_iter = kwargs.get("max_iter", np.inf)
    seen_states = set()
    for state in q[1]:
        seen_states.update(state.keys())

    global_seen_size = np.array([len(seen_states)], dtype=int)
    if mpi:
        comm.Allreduce(MPI.IN_PLACE, global_seen_size, op=MPI.SUM)

    while it * n < global_seen_size[0] and it < max_iter:
        wp = matmat(q[1])

        for state in wp:
            seen_states.update(state.keys())
        global_seen_size[0] = len(seen_states)
        if mpi:
            comm.Allreduce(MPI.IN_PLACE, global_seen_size, op=MPI.SUM)

        alpha_i = inner_multi(q[1], wp)
        if mpi:
            comm.Allreduce(MPI.IN_PLACE, alpha_i, op=MPI.SUM)

        alphas = np.append(alphas, [alpha_i], axis=0)
        betas = np.append(betas, np.zeros((1, n, n), dtype=complex), axis=0)

        add_scaled_multi(wp, q[1], -alpha_i)

        if it > 0:
            beta_prev_dag = np.conj(betas[it - 1].T)
            add_scaled_multi(wp, q[0], -beta_prev_dag)

        inner_multi(Q, wp)
        if reort == Reort.FULL or (reort == Reort.PERIODIC and it > 0 and it % period == 0):
            if not build_krylov_basis:
                raise RuntimeError("Krylov basis must be built for reorthogonalization")
            _reorthogonalize_sparse(wp, Q, None, inner, mpi, comm, n)

        M = inner_multi(wp, wp)
        if mpi:
            comm.Allreduce(MPI.IN_PLACE, M, op=MPI.SUM)

        if np.any(np.isnan(M)) or np.any(np.isinf(M)):
            # If M is invalid, the previous block was bad. We must remove the last appended alpha and beta.
            alphas = alphas[:-1]
            betas = betas[:-1]
            if build_krylov_basis:
                Q = Q[:-n]
            break

        if np.linalg.cond(M) > 1 / (100 * np.finfo(float).eps):
            # Breakdown: block is linearly dependent, stop expanding
            break

        try:
            L = sp.linalg.cholesky(M, lower=True)
        except sp.linalg.LinAlgError:
            break

        beta_i = np.conj(L.T)
        betas[it] = beta_i

        if reort in (Reort.PARTIAL, Reort.SELECTIVE):
            if not build_krylov_basis:
                raise RuntimeError("Krylov basis must be built for reorthogonalization")
            if W is None:
                if track_full_W:
                    W = np.zeros((1, 1, n, n), dtype=complex)
                    W[0, 0] = np.eye(n)
                else:
                    W = np.zeros((2, 1, n, n), dtype=complex)
                    W[1, 0] = np.eye(n)
            elif W.shape[0] < it + 1 or W.shape[1] < it + 1:
                if track_full_W:
                    W_new = np.zeros((it + 1, it + 1, n, n), dtype=complex)
                    W_new[: W.shape[0], : W.shape[1]] = W
                    W = W_new
                else:
                    W_new = np.zeros((2, it + 1, n, n), dtype=complex)
                    W_new[:, : W.shape[1]] = W
                    W = W_new
            W = estimate_orthonormality(W, alphas[: it + 1], betas[: it + 1], eps=np.finfo(float).eps)
            if it > 0 and np.max(np.abs(W[-1, : it + 1])) > reort_eps:
                bad_block_indices = [j for j in range(it + 1) if np.max(np.abs(W[-1, j])) > reort_eps * 1e-2]
                bad_state_indices = [j * n + k for j in bad_block_indices for k in range(n)]
                bad_state_indices_prev = [idx for idx in bad_state_indices if idx < len(Q) - n]
                if reort == Reort.PARTIAL:
                    _reorthogonalize_sparse(Q[-n:], Q[:-n], bad_state_indices_prev, inner, mpi, comm, n)
                    _reorthogonalize_sparse(wp, Q, bad_state_indices, inner, mpi, comm, n)
                elif reort == Reort.SELECTIVE:
                    eigvals, eigvecs = eigsh(alphas[: it + 1], betas[: it + 1], select="a", max_ev=0)
                    error_bounds = np.linalg.norm(betas[it], ord=2) * np.abs(eigvecs[-n:, :]).max(axis=0)
                    converged_mask = error_bounds < reort_eps
                    if np.any(converged_mask):
                        converged_Ritz = [ManyBodyState() for _ in range(np.sum(converged_mask))]
                        converged_eigvecs = eigvecs[:, converged_mask]
                        for ritz_idx in range(np.sum(converged_mask)):
                            for q_idx, qq in enumerate(Q):
                                converged_Ritz[ritz_idx] += qq * converged_eigvecs[q_idx, ritz_idx]
                        _reorthogonalize_sparse(Q[-n:], converged_Ritz, None, inner, mpi, comm, n)
                        _reorthogonalize_sparse(wp, converged_Ritz, None, inner, mpi, comm, n)
                    _reorthogonalize_sparse(Q[-n:], Q[:-n], bad_state_indices_prev, inner, mpi, comm, n)
                    _reorthogonalize_sparse(wp, Q, bad_state_indices, inner, mpi, comm, n)

                # Ensure the previous step vectors q[1] (which is a reference or copy of Q[-n:]) is updated
                for st, q_st in zip(q[1], Q[-n:]):
                    st.clear()
                    for state, amp in q_st.items():
                        st[state] = amp

                # Recompute M, L, beta_i
                M = inner_multi(wp, wp)
                if mpi:
                    comm.Allreduce(MPI.IN_PLACE, M, op=MPI.SUM)

                if np.any(np.isnan(M)) or np.any(np.isinf(M)):
                    alphas = alphas[:-1]
                    betas = betas[:-1]
                    if build_krylov_basis:
                        Q = Q[:-n]
                    break

                try:
                    if np.linalg.cond(M) > 1 / (100 * np.finfo(float).eps):
                        alphas = alphas[:-1]
                        betas = betas[:-1]
                        if build_krylov_basis:
                            Q = Q[:-n]
                        break
                    L = sp.linalg.cholesky(M, lower=True)
                except sp.linalg.LinAlgError:
                    alphas = alphas[:-1]
                    betas = betas[:-1]
                    if build_krylov_basis:
                        Q = Q[:-n]
                    break
                beta_i = np.conj(L.T)
                betas[it] = beta_i
                # Reset the estimated overlaps for the current and past iteration
                bad_block_indices_prev = [j for j in bad_block_indices if j < it]
                eps = np.finfo(float).eps
                W[-1, bad_block_indices] = eps * np.eye(n)
                if track_full_W:
                    W[-2, bad_block_indices_prev] = eps * np.eye(n)
                else:
                    W[0, bad_block_indices_prev] = eps * np.eye(n)

        import warnings

        try:
            with warnings.catch_warnings():
                warnings.simplefilter("error")
                beta_inv = sp.linalg.inv(beta_i)
        except Exception:
            break

        q_next = [ManyBodyState() for _ in range(n)]
        add_scaled_multi(q_next, wp, beta_inv)

        for st in q_next:
            st.prune(slaterWeightMin)

        if converged(alphas, betas, verbose=verbose):
            break

        q[0] = q[1]
        q[1] = q_next
        if build_krylov_basis:
            Q.extend([st.copy() for st in q_next])
        it += 1

    if verbose:
        print(f"Coverged at iteration {it + 1} out of a maximum of {basis.size // n}")
    if return_W:
        return alphas, betas, Q if build_krylov_basis else None, W
    return alphas, betas, Q if build_krylov_basis else None


def get_Lanczos_vectors(A, alphas, betas, v0, comm, which="all"):
    """
    Reconstruct Lanczos vectors from alphas, betas, and initial vector v0.

    Parameters
    ----------
    A : scipy.sparse.linalg.LinearOperator or ndarray
        The Hamiltonian/operator used in the Lanczos recursion.
    alphas : ndarray
        The diagonal block matrices (alpha) generated by block Lanczos.
        Shape: `(n_iterations, block_size, block_size)`.
    betas : ndarray
        The off-diagonal block matrices (beta) generated by block Lanczos.
        Shape: `(n_iterations, block_size, block_size)`.
    v0 : ndarray
        The initial starting block of vectors. Shape: `(local_basis_size, block_size)`.
    comm : mpi4py.MPI.Comm or None
        MPI communicator for parallel computation.
    which : str, int, list, or tuple, optional
        Specifies which Krylov block vectors to return. Options are:
        - `"all"`: return all vectors.
        - `int`: return the block at this index (can be negative for index from end).
        - `list` or `tuple`: return blocks at these indices.
        Default is `"all"`.

    Returns
    -------
    Q : ndarray
        The reconstructed Lanczos vectors matching the requested indices.
        Shape: `(local_basis_size, len(which) * block_size)`.
    """
    mpi = comm is not None
    rank = comm.rank if mpi else 0
    counts = np.array([v0.size], dtype=int)
    offsets = np.array([0], dtype=int)
    n_it = alphas.shape[0]
    N = v0.shape[0]
    n = alphas.shape[1]
    q = np.empty((2, 0, 0), dtype=complex)
    if rank == 0:
        q = np.zeros((2, A.shape[0], n), dtype=complex, order="C")
    if mpi:
        counts = np.empty((comm.size), dtype=int)
        comm.Allgather(np.array([v0.size], dtype=int), counts)
        offsets = np.array([np.sum(counts[:r]) for r in range(comm.size)], dtype=int)
        comm.Gatherv(v0, (q[1] if rank == 0 else None, counts, offsets, MPI.C_DOUBLE_COMPLEX))
    else:
        q[1] = v0
    assert (n_it + 1) * n == (alphas.shape[0] + 1) * alphas.shape[1]
    if which == "all":
        which = list(range(n_it))
    elif isinstance(which, int):
        if which < 0:
            which = [n_it + which]
        else:
            which = [which]
    elif isinstance(which, list):
        which = [w if w >= 0 else n_it + w for w in which]
    elif isinstance(which, tuple):
        which = list(range(min(which[0], which[1]), max(which[0], which[1])))
    else:
        raise RuntimeError(f"Unknown value for which: {which}")

    Q = np.empty((N, len(which) * n), dtype=alphas.dtype)
    which_dict = {val: idx for idx, val in enumerate(which)}
    qi = v0.copy()
    for i in range(n_it):
        if i in which_dict:
            idx = which_dict[i]
            Q[:, idx * n : (idx + 1) * n] = qi
        q_tmp = A @ qi
        if mpi and not isinstance(A, sp.sparse.linalg.LinearOperator):
            comm.Reduce(MPI.IN_PLACE if rank == 0 else q_tmp, q_tmp, op=MPI.SUM, root=0)
        if rank == 0:
            if i == 0:
                q_tmp -= q[1] @ alphas[i]
            else:
                q_tmp -= q[1] @ alphas[i] + q[0] @ np.conj(betas[i - 1].T)
            q[0] = q[1]
            q[1], _ = sp.linalg.qr(q_tmp, mode="economic", overwrite_a=True, check_finite=False)
        if mpi:
            comm.Scatterv(
                (q[1], counts, offsets, MPI.C_DOUBLE_COMPLEX),
                qi,
                root=0,
            )
        else:
            qi = q[1]
    if n_it in which_dict:
        idx = which_dict[n_it]
        Q[:, idx * n : (idx + 1) * n] = qi

    return Q
