"""Tests for the ``.h0`` interchange format (``doc/h0_file_format.md``).

The fixtures are **hand-authored from the spec**, not generated by either implementation.
That is deliberate: rspt2spectra and impurityModel implement the format independently, so a
fixture produced by one of them would only prove that implementation self-consistent, and
whichever repo generated it would have to land first before the other could test anything.
"""

import json
from pathlib import Path

import numpy as np
import pytest

from impurityModel.ed import h0_format
from impurityModel.ed.h0_format import H0FormatError

FIXTURES = Path(__file__).parent
INDEX_FIXTURE = FIXTURES / "golden_h0_v1_index.h0"
RYDBERG_FIXTURE = FIXTURES / "golden_h0_v1_rydberg.h0"


def _header_of(path):
    text = path.read_text()
    return json.loads(text.splitlines()[1])


def _rewrite(tmp_path, name, *, header_update=None, terms=None, source=INDEX_FIXTURE):
    """Copy a fixture with its header patched and/or its terms replaced."""
    lines = source.read_text().splitlines()
    header = json.loads(lines[1])
    header.update(header_update or {})
    body = terms if terms is not None else lines[3:]
    out = tmp_path / name
    out.write_text("\n".join([lines[0], json.dumps(header), "--", *body]) + "\n")
    return out


# --------------------------------------------------------------------------------------
# The index fixture: values encode their own indices, so any permutation, transpose or
# conjugation error changes the asserted result.
# --------------------------------------------------------------------------------------


def test_index_fixture_exact_operator_dict():
    parsed = h0_format.read_h0_file(INDEX_FIXTURE)

    assert parsed.n_orb == 8
    assert parsed.impurity_orbitals == {0: (0, 1, 2, 3)}
    assert parsed.impurity_indices == [0, 1, 2, 3]
    assert parsed.n_imp == 4
    assert parsed.valence_bath == (4, 5)
    assert parsed.conduction_bath == (6, 7)
    assert parsed.unit == "eV"
    assert parsed.energy_reference == "fermi"
    assert parsed.basis == "spherical"
    assert parsed.contains_soc is False

    # The fixture is the Hermitian part of H[i, j] = (10i + j) + 0.5j*(i - j), i.e.
    # 5.5*(i + j) + 0.5j*(i - j). The real part fixes the index *sum* and the imaginary part
    # the signed difference, so no permutation, transpose or conjugation can go unnoticed.
    h = parsed.to_matrix()
    expected = np.array([[5.5 * (i + j) + 0.5j * (i - j) for j in range(8)] for i in range(8)])
    np.testing.assert_array_equal(h, expected)


def test_index_fixture_is_hermitian_and_diagonal_is_real():
    h = h0_format.read_h0_file(INDEX_FIXTURE).to_matrix()
    np.testing.assert_array_equal(h, h.conj().T)
    np.testing.assert_array_equal(h.diagonal().imag, np.zeros(8))


def test_rydberg_fixture_is_converted_to_ev():
    parsed = h0_format.read_h0_file(RYDBERG_FIXTURE)

    assert parsed.unit == "eV"
    assert parsed.header["unit"] == "Ry"
    # The conversion is asserted on the value, not merely on the key being present.
    assert parsed.h0[((0, "c"), (0, "a"))] == pytest.approx(1.0 * h0_format.RY_TO_EV)
    assert parsed.h0[((0, "c"), (2, "a"))] == pytest.approx(0.25 * h0_format.RY_TO_EV)


# --------------------------------------------------------------------------------------
# Round trip
# --------------------------------------------------------------------------------------


def test_round_trip_is_exact(tmp_path):
    """Exact dict equality, not assert_allclose: repr floats make it achievable.

    A tolerance-based comparison would be blind to a dropped term, which is the failure
    mode that actually occurred with the predecessor's fixed-point format.
    """
    original = h0_format.read_h0_file(INDEX_FIXTURE)
    out = tmp_path / "round_trip.h0"
    h0_format.write_h0_file(out, original.to_matrix(), impurity_orbitals=original.impurity_orbitals)

    reread = h0_format.read_h0_file(out)
    assert reread.h0 == original.h0
    assert reread.n_orb == original.n_orb
    assert reread.impurity_orbitals == original.impurity_orbitals


def test_round_trip_survives_awkward_magnitudes(tmp_path):
    """Small elements round-trip bit-for-bit; %.15f wrote these with 4 digits, or as 0.

    drop_tolerance=0 isolates precision from the scale-relative drop rule -- the 1e-10 and
    1e-12 elements here are genuine f-shell magnitudes, and at the default 1e-12 relative
    threshold they would legitimately be discarded next to the 1234 element.
    """
    h = np.zeros((3, 3), dtype=complex)
    h[0, 0] = -4.126921785541874
    h[0, 1] = 1.2345678901234567e-10 + 6.599434672757963e-12j
    h[1, 0] = np.conj(h[0, 1])
    h[2, 2] = 1234.5678901234567

    out = tmp_path / "small.h0"
    h0_format.write_h0_file(out, h, impurity_orbitals={0: [0, 1]}, drop_tolerance=0.0)
    np.testing.assert_array_equal(h0_format.read_h0_file(out).to_matrix(), h)


def test_default_drop_tolerance_is_scale_relative(tmp_path):
    """The threshold is relative to max|H| and applied to the (i,j)/(j,i) pair together."""
    h = np.diag([1000.0, 1.0, 1.0]).astype(complex)
    h[1, 2] = 1e-10  # below the 1e-12 * 1000 = 1e-9 cutoff, though large next to |H[1,1]|
    h[2, 1] = 1e-10

    out = tmp_path / "rel.h0"
    h0_format.write_h0_file(out, h, impurity_orbitals={0: [0]})
    got = h0_format.read_h0_file(out).to_matrix()
    assert got[1, 2] == 0.0 and got[2, 1] == 0.0
    assert got[0, 0] == 1000.0


def test_writer_symmetrizes_and_drops_pairwise(tmp_path):
    """A non-Hermitian input is symmetrized, and negligible pairs leave with both halves."""
    h = np.array([[1.0, 3.0, 1e-18], [1.0, 2.0, 0.0], [0.0, 0.0, 4.0]], dtype=complex)
    out = tmp_path / "sym.h0"
    h0_format.write_h0_file(out, h, impurity_orbitals={0: [0, 1]})

    got = h0_format.read_h0_file(out).to_matrix()
    assert got[0, 1] == 2.0 and got[1, 0] == 2.0
    # Below drop_tolerance * max|H|; the (2,0) partner goes with it, so the key sets match.
    assert got[0, 2] == 0.0 and got[2, 0] == 0.0


def test_writer_rejects_non_finite(tmp_path):
    with pytest.raises(H0FormatError, match="non-finite"):
        h0_format.write_h0_file(tmp_path / "nan.h0", np.array([[np.nan]]), impurity_orbitals={0: [0]})


# --------------------------------------------------------------------------------------
# Robust parsing
# --------------------------------------------------------------------------------------


@pytest.mark.parametrize("transform", ["crlf", "bom", "no_trailing_newline", "cr"])
def test_byte_level_variations_parse_identically(tmp_path, transform):
    reference = h0_format.read_h0_file(INDEX_FIXTURE).h0
    raw = INDEX_FIXTURE.read_bytes()
    if transform == "crlf":
        raw = raw.replace(b"\n", b"\r\n")
    elif transform == "cr":
        raw = raw.replace(b"\n", b"\r")
    elif transform == "bom":
        raw = b"\xef\xbb\xbf" + raw
    else:
        raw = raw.rstrip(b"\n")

    out = tmp_path / f"{transform}.h0"
    out.write_bytes(raw)
    assert h0_format.read_h0_file(out).h0 == reference


def test_double_dash_inside_a_json_string_does_not_truncate_the_header(tmp_path):
    """The `--` separator is cosmetic; the header's extent comes from JSON's grammar."""
    out = _rewrite(tmp_path, "dashes.h0", header_update={"producer": {"name": "a--b"}})
    parsed = h0_format.read_h0_file(out)
    assert parsed.header["producer"]["name"] == "a--b"
    assert parsed.n_orb == 8


def test_comments_and_blank_lines_between_terms_are_ignored(tmp_path):
    out = _rewrite(tmp_path, "comments.h0", terms=["0 0 1.0 0.0", "", "# a comment", "  ", "1 1 2.0 0.0"])
    parsed = h0_format.read_h0_file(out)
    assert parsed.h0 == {((0, "c"), (0, "a")): 1.0 + 0j, ((1, "c"), (1, "a")): 2.0 + 0j}


# --------------------------------------------------------------------------------------
# Negative cases -- each must raise a named, typed error
# --------------------------------------------------------------------------------------


def test_empty_file_raises(tmp_path):
    empty = tmp_path / "empty.h0"
    empty.write_text("")
    with pytest.raises(H0FormatError, match="empty"):
        h0_format.read_h0_file(empty)


def test_missing_magic_line_is_reported_as_legacy(tmp_path):
    """A legacy file renamed to .h0 must be diagnosed, not mis-parsed."""
    legacy = tmp_path / "renamed.h0"
    legacy.write_text("  0   0 -4.125093021114729  0.000000000000000\n")
    with pytest.raises(H0FormatError, match="magic line"):
        h0_format.read_h0_file(legacy)


def test_future_version_raises(tmp_path):
    out = tmp_path / "v99.h0"
    out.write_text("# impurityModel-h0 v99\n" + INDEX_FIXTURE.read_text().split("\n", 1)[1])
    with pytest.raises(H0FormatError, match="v99"):
        h0_format.read_h0_file(out)


def test_unknown_required_feature_raises(tmp_path):
    out = _rewrite(tmp_path, "feature.h0", header_update={"required_features": ["quantum_gravity"]})
    with pytest.raises(H0FormatError, match="quantum_gravity"):
        h0_format.read_h0_file(out)


def test_unknown_index_convention_raises(tmp_path):
    out = _rewrite(tmp_path, "conv.h0", header_update={"index_convention": "bath-first"})
    with pytest.raises(H0FormatError, match="index_convention"):
        h0_format.read_h0_file(out)


@pytest.mark.parametrize(
    "update, pattern",
    [
        ({"unit": "hartree"}, "unknown unit"),
        ({"storage": "upper"}, "storage"),
    ],
)
def test_bad_header_values_raise(tmp_path, update, pattern):
    with pytest.raises(H0FormatError, match=pattern):
        h0_format.read_h0_file(_rewrite(tmp_path, "bad.h0", header_update=update))


@pytest.mark.parametrize("missing", ["unit", "energy_reference", "impurity_orbitals"])
def test_missing_mandatory_key_raises(tmp_path, missing):
    header = _header_of(INDEX_FIXTURE)
    del header[missing]
    lines = INDEX_FIXTURE.read_text().splitlines()
    out = tmp_path / "missing.h0"
    out.write_text("\n".join([lines[0], json.dumps(header), "--", *lines[3:]]) + "\n")
    with pytest.raises(H0FormatError, match=missing):
        h0_format.read_h0_file(out)


def test_malformed_json_header_raises(tmp_path):
    out = tmp_path / "badjson.h0"
    out.write_text('# impurityModel-h0 v1\n{"version": 1,\n--\n0 0 1.0 0.0\n')
    with pytest.raises(H0FormatError, match="JSON"):
        h0_format.read_h0_file(out)


def test_non_hermitian_raises_naming_the_element(tmp_path):
    out = _rewrite(tmp_path, "nonherm.h0", terms=["0 1 1.0 0.0"])
    with pytest.raises(H0FormatError, match=r"H\[0,1\].*conjugate partner absent"):
        h0_format.read_h0_file(out)


def test_index_outside_n_orb_raises(tmp_path):
    out = _rewrite(tmp_path, "range.h0", terms=["8 8 1.0 0.0"])
    with pytest.raises(H0FormatError, match="outside n_orb"):
        h0_format.read_h0_file(out)


@pytest.mark.parametrize(
    "bad_term, pattern",
    [
        ("0 0 1.0", "4 whitespace-separated fields"),
        ("0 0 1.0 0.0 0.0", "4 whitespace-separated fields"),
        ("a 0 1.0 0.0", "integer orbital indices"),
        ("0 0 x 0.0", "real amplitudes"),
        ("0 0 nan 0.0", "must be finite"),
        ("0 0 1.0 inf", "must be finite"),
    ],
)
def test_malformed_term_line_raises_with_line_number(tmp_path, bad_term, pattern):
    out = _rewrite(tmp_path, "term.h0", terms=[bad_term])
    with pytest.raises(H0FormatError, match=pattern) as excinfo:
        h0_format.read_h0_file(out)
    assert "term.h0:4:" in str(excinfo.value)


def test_duplicate_index_pair_raises(tmp_path):
    out = _rewrite(tmp_path, "dup.h0", terms=["0 0 1.0 0.0", "0 0 2.0 0.0"])
    with pytest.raises(H0FormatError, match="duplicate index pair"):
        h0_format.read_h0_file(out)


def test_unknown_header_key_is_ignored(tmp_path):
    out = _rewrite(tmp_path, "extra.h0", header_update={"something_new": 42})
    assert h0_format.read_h0_file(out).n_orb == 8


def test_hartree_is_exactly_two_rydberg():
    """``HA_TO_EV`` is derived from ``RY_TO_EV`` rather than being a second CODATA literal.

    Hartree is two Rydberg *by definition*, so deriving it keeps the two constants from
    drifting apart by independent rounding -- the same no-duplicated-constants rule the rest
    of the package follows for tolerances.
    """
    assert h0_format.HA_TO_EV == 2.0 * h0_format.RY_TO_EV
    assert h0_format.HA_TO_EV == pytest.approx(27.211386245988, rel=1e-12)


def test_energy_units_covers_ha_but_the_h0_header_does_not():
    """The scope split: callers may convert *from* Hartree, a ``.h0`` header may not declare it.

    Widening what the on-disk format accepts is a format change needing its own
    ``required_features`` story, and no producer writes Hartree, so ``_KNOWN_UNITS`` stays as
    it was while ``ENERGY_UNITS`` (which the TOML input format uses) gains the entry.
    """
    assert set(h0_format.ENERGY_UNITS) == {"eV", "Ry", "Ha"}
    assert set(h0_format._KNOWN_UNITS) == {"eV", "Ry"}
    for unit, factor in h0_format._KNOWN_UNITS.items():
        assert h0_format.ENERGY_UNITS[unit] == factor


def test_a_h0_declaring_hartree_is_still_refused(tmp_path):
    """Guards the split above: adding ``Ha`` to ``ENERGY_UNITS`` must not leak into the reader."""
    out = _rewrite(tmp_path, "hartree.h0", header_update={"unit": "Ha"})
    with pytest.raises(H0FormatError, match="unit"):
        h0_format.read_h0_file(out)


def test_the_rich_header_rspt2spectra_writes_is_promoted(tmp_path):
    """``build_h0`` records far more than the reader used to expose.

    ``impurity_l`` names *which* shell the stored bath belongs to, ``bath_geometry`` says
    whether the valence/conduction labels were recorded at all, and ``fermi_energy`` is what
    makes ``energy_reference: "fermi"`` auditable instead of merely asserted. All three were
    reaching consumers only as raw-dict lookups.
    """
    out = _rewrite(
        tmp_path,
        "rich.h0",
        header_update={
            "impurity_l": 2,
            "fermi_energy": 0.5,
            "bath_geometry": "star",
            "producer": {"name": "rspt2spectra", "cluster": "Ni"},
        },
    )
    parsed = h0_format.read_h0_file(out)
    assert parsed.impurity_l == 2
    assert parsed.fermi_energy == pytest.approx(0.5)
    assert parsed.bath_geometry == "star"
    assert parsed.producer["cluster"] == "Ni"


def test_the_fermi_energy_is_converted_like_every_other_energy(tmp_path):
    """It is an energy in the file's own unit, so it must not survive the read unscaled."""
    out = _rewrite(tmp_path, "ry.h0", header_update={"unit": "Ry", "fermi_energy": 1.0})
    assert h0_format.read_h0_file(out).fermi_energy == pytest.approx(h0_format.RY_TO_EV)
