r"""Does the gap criterion's ``omega_+-`` carry any impurity spectral weight?

:func:`dc_criteria.fixed_gap_dc` centres ``(E_0[N+1] - E_0[N-1])/2`` on the Fermi level, where
each ``E_0`` is the *lowest* eigenvalue of a charge sector. Karolak et al.'s prescription is about
the gap of the local spectral function

.. math:: A_{\rm imp}(\omega) = -\tfrac{1}{\pi}\,{\rm Im}\,G_{\rm imp}(\omega + i0^+),

whose Lehmann representation puts the addition edge at

.. math:: \omega_+ = \min\{\,E_n[N+1] - E_0[N] \;:\; w_n > 0\,\},
          \qquad w_n = \sum_d |\langle n|c_d^\dagger|0\rangle|^2 .

Taking the minimum over **all** ``n`` rather than over the weighted ones is an assumption, not an
identity, and it fails in two independent ways: the lowest addition state can be a *bath* level
(generic in a bath-discretized model -- it is what a hybridization fit puts near ``E_F``), or it
can differ from ``c_d^\dagger|0\rangle`` by spin or irrep, in which case the weight is **exactly**
zero. This module measures ``w_n`` so the two can be told apart, and told apart from the third
possibility: that the model has no impurity gap at all.

**No common basis is needed, and that is the design.** An earlier attempt built one determinant
space spanning ``N-1, N, N+1`` (``dc_criteria.build_union_space``) so the overlaps would share an
index space. It does not work: ``H`` conserves the electron number and CIPSI expands from the
centre sector's reference, so the ``N +- 1`` blocks never grow past whatever
``generate_initial_basis`` seeded -- measured on the charge-transfer fixture, **one determinant
each** against 18 in the centre. A ``ManyBodyState`` is keyed by determinant, so
``<psi_n | c_d^dagger psi_0>`` is a sum over the intersection of two supports and needs no shared
``Basis`` at all. Each sector then keeps its own properly expanded space, which also means the
energies here are the ones :func:`dc_criteria.fixed_gap_dc` actually uses rather than a frozen-space
model of them.

Serial only. The overlaps and the representability check are new reductions over determinants, and
the last pass through this code shipped a deadlock; determinants are hash-distributed so an
MPI version is possible, but nothing here needs it (see CLAUDE.md's MPI rules before adding one).

Run as an opt-in benchmark module, or directly::

    python -m impurityModel.test.support.dc_weights nio_5peeled 2000 -0.2587
"""

from dataclasses import replace

import numpy as np
from mpi4py import MPI

from impurityModel.ed.basis_transcription import build_density_matrices
from impurityModel.ed.dc_criteria import _per_group_occupation, _prepare_sector_context
from impurityModel.ed.groundstate import solve_sector
from impurityModel.ed.operator_algebra import ManyBodyOperator

#: Eigenpairs per sector. Ten (``calc_energy``'s number) is a thermal manifold, not a spectrum:
#: the lowest states of an ``N +- 1`` sector can all be bath excitations, and the whole question
#: here is how far above the lowest one the first *weighted* state sits.
DEFAULT_NUM_STATES = 40

#: Fraction of a sector's enumerated addition/removal weight a state must carry to count as an
#: edge. Not a physical constant -- it is the level below which a pole is invisible in
#: ``A_imp(omega)`` next to the ones around it, and it is reported alongside every number derived
#: from it so a reader can re-cut the table at their own threshold.
DEFAULT_WEIGHT_FRACTION = 0.05


def _overlap(psi_a, psi_b):
    """``<psi_a | psi_b>`` for two ``ManyBodyState``s that need not share a basis.

    Both are dictionaries keyed by determinant, so the inner product is a sum over the
    intersection of their supports. Iterating the shorter one keeps this linear in the smaller
    support rather than in the larger.
    """
    items_a, items_b = dict(psi_a.items()), dict(psi_b.items())
    if len(items_b) < len(items_a):
        items_a, items_b = items_b, items_a
        conj_first = False
    else:
        conj_first = True
    total = 0.0 + 0.0j
    for state, amp in items_a.items():
        other = items_b.get(state)
        if other is None:
            continue
        a, b = complex(amp[0]), complex(other[0])
        total += np.conj(a) * b if conj_first else np.conj(b) * a
    return total


def _norm2(psi):
    """``<psi|psi>``, over the state's own support."""
    return float(sum(abs(complex(amp[0])) ** 2 for _state, amp in psi.items()))


def _supported_norm2(psi, basis):
    """The part of ``<psi|psi>`` that lives on determinants ``basis`` actually holds.

    Divided by :func:`_norm2` this is the *representability* of the seed: whether the sector's
    CIPSI basis contains the support of ``c_d^dagger|0>`` at all. It is not 1 by construction --
    the seed is generated by an operator the expansion never saw -- and below ~0.9 every weight
    below it describes a truncated seed rather than the state.
    """
    return float(sum(abs(complex(amp[0])) ** 2 for state, amp in psi.items() if state in basis))


def spectral_moments(h_op, psi_ground, e_ground, imp_flat):
    r"""The exact zeroth and first moments of ``A_imp``, per side, with no enumeration at all.

    .. math::
        M_0^\pm = \sum_n w_n^\pm, \qquad M_1^\pm = \sum_n w_n^\pm\,\omega_n^\pm

    are ground-state expectation values, because the sums close by completeness:

    .. math::
        M_0^+ = \langle 0|c_d c_d^\dagger|0\rangle = 1 - n_d, \qquad
        M_1^+ = \langle 0|c_d\,H\,c_d^\dagger|0\rangle - E_0 (1 - n_d),

    and the removal partners with ``c_d`` and ``n_d``. So ``M_1/M_0`` -- the centre of gravity of
    each side of the impurity spectral function -- costs one application of ``H`` per impurity
    orbital and is **exact**, where the enumerated centroid inherits every state the window
    missed. On NiO's removal side that difference is not academic: 60 states reach 55 % of the
    sum rule, and the enumerated centroid moves by 4.5 eV between two determinant caps while the
    moments do not move at all.

    A centre of gravity is not an edge, and this is not proposed as a criterion. It is the one
    threshold-free statement available about where the impurity weight actually sits, which is
    what makes it the honest companion to ``omega_+-``.

    Returns
    -------
    dict
        ``m0_plus``, ``m1_plus``, ``centroid_plus`` and the removal partners, plus
        ``centre_moment = (centroid_plus + centroid_minus)/2``.
    """
    out = {}
    for tag, kind in (("plus", "c"), ("minus", "a")):
        m0 = m1 = 0.0
        for orb in imp_flat:
            phi = ManyBodyOperator({((orb, kind),): 1.0})(psi_ground, 0)
            norm2 = _norm2(phi)
            expectation = float(np.real(_overlap(phi, h_op(phi, 0))))
            m0 += norm2
            # omega is E_n - E_0 for addition and E_0 - E_n for removal, matching the pole
            # positions the record's omega_+- use.
            m1 += (expectation - e_ground * norm2) if kind == "c" else (e_ground * norm2 - expectation)
        out[f"m0_{tag}"] = m0
        out[f"m1_{tag}"] = m1
        out[f"centroid_{tag}"] = None if m0 == 0 else m1 / m0
    out["centre_moment"] = _centre(out["centroid_plus"], out["centroid_minus"])
    return out


def _sector_states(ctx, h_op, n_trial, num_states, max_energy):
    """``(es, psis, basis)`` for one sector, on :func:`dc_criteria._SectorContext`'s conventions.

    Mirrors :meth:`_SectorContext.sector_energy` exactly -- same bounds check, same arguments --
    except that it keeps the eigenvectors. ``(None, None, None)`` where that method returns
    ``None``, i.e. where the criterion is *undefined* rather than merely large.
    """
    if not 0 <= n_trial <= ctx.max_occ_total:
        return None, None, None
    occ_trial = _per_group_occupation(n_trial, ctx.impurity_orbitals, ctx.h_solver_matrix)
    es, psis, basis = solve_sector(
        h_op,
        ctx.impurity_orbitals,
        ctx.bath_states,
        occ_trial,
        ctx.mixed_valence,
        ctx.tau,
        ctx.chain_restrict,
        ctx.spin_flip_dj,
        ctx.dense_cutoff,
        comm=MPI.COMM_WORLD,
        verbose=ctx.verbose,
        truncation_threshold=ctx.truncation_threshold,
        slaterWeightMin=ctx.slater_weight_min,
        weighted_restrictions=ctx.weighted_restrictions,
        frozen_occupations=ctx.frozen_occupations,
        num_wanted=num_states,
        max_energy=max_energy,
    )
    if not np.all(np.isfinite(es)):
        return None, None, None
    return es, psis, basis


def sector_weight_table(
    model,
    basis_options,
    solver_options,
    mu,
    *,
    num_states=DEFAULT_NUM_STATES,
    max_energy=None,
    weight_fraction=DEFAULT_WEIGHT_FRACTION,
    comm=None,
    verbosity=0,
):
    r"""Per-state energy, impurity occupation and Lehmann weight for ``N-1``, ``N``, ``N+1``.

    Parameters
    ----------
    mu : float
        The trial double-counting shift, in ``dc = dc_guess + mu * identity`` -- the same
        coordinate :func:`dc_criteria.fixed_gap_dc` searches over.
    max_energy : float, optional
        Cut on ``e - e0`` per sector. Defaults to the full one-body bandwidth, which is far above
        the Boltzmann cut ``solve_sector`` would otherwise apply and is what makes this an
        enumeration rather than a thermal manifold. It has to reach the *upper Hubbard band*: on
        the charge-transfer fixture the impurity addition pole sits at ``eps + U - dc``, well
        above the bath level near ``E_F``, and a window that stops short of it enumerates only
        the bath weight and reports it as the whole spectrum.

    Returns
    -------
    dict
        ``n_center``, ``omega_plus``/``omega_minus`` (the criterion's own unweighted edges),
        ``omega_plus_w``/``omega_minus_w`` (the first state above ``weight_fraction``),
        ``centre``/``centre_w``, the per-sector ``states`` tables, the representability of each
        seed, and the enumerated weight against the exact sum rule.
    """
    comm = MPI.COMM_WORLD if comm is None else comm
    if comm.size > 1:
        raise RuntimeError(
            "dc_weights is serial only: the overlaps and the representability check are "
            "reductions over determinant supports that have no distributed implementation here. "
            "Run without mpiexec (the sector solves inside are the same collective code either "
            "way, so nothing about the physics changes)."
        )
    ctx = _prepare_sector_context(
        model, basis_options, solver_options, comm=comm, verbosity=verbosity, memory_label="dc weight diagnostic"
    )
    if max_energy is None:
        max_energy = ctx.bandwidth

    h_op = ctx.shifted_h(mu)
    n_center = ctx.centre_sector(h_op, mu)
    imp_indices = ctx.impurity_orbitals
    imp_flat = [orb for blocks in imp_indices.values() for block in blocks for orb in block]

    sectors = {}
    for n in (n_center - 1, n_center, n_center + 1):
        es, psis, sector_basis = _sector_states(ctx, h_op, n, num_states, max_energy)
        sectors[n] = None if es is None else (es, psis, sector_basis)

    if sectors[n_center] is None:
        raise RuntimeError(f"the centre sector {n_center} is unreachable at mu = {mu}; nothing to measure")
    es_c, psis_c, basis_c = sectors[n_center]
    order = np.argsort(np.real(es_c))
    e_ground = float(np.real(es_c[order[0]]))
    psi_ground = psis_c[order[0]]

    # <n_d> in the ground state: the exact sum rules the enumerated weights are checked against
    # (sum_n w_n = sum_d (1 - n_d) for addition, sum_d n_d for removal).
    rho_ground = build_density_matrices(basis_c, [psi_ground], imp_flat, imp_flat)[0]
    n_ground = float(np.real(np.trace(rho_ground)))
    occupations = np.real(np.diag(rho_ground))
    sum_rule = {n_center + 1: float(np.sum(1.0 - occupations)), n_center - 1: float(n_ground)}

    # The seeds. Built from the *solver*-basis impurity indices, exactly as
    # `build_density_matrices` builds its annihilators -- never from
    # `transition_operators.inverse_photoemission_operators`, which indexes through
    # `c2i(nBaths, (l,s,m))` in the spherical convention. A mismatch between the two index spaces
    # produces entirely plausible weights for the wrong orbitals.
    #
    # These operators carry no restrictions: a restricted apply would silently drop exactly the
    # determinants the representability check below exists to count, so the check would pass
    # unconditionally.
    seeds = {
        n_center + 1: [ManyBodyOperator({((orb, "c"),): 1.0})(psi_ground, 0) for orb in imp_flat],
        n_center - 1: [ManyBodyOperator({((orb, "a"),): 1.0})(psi_ground, 0) for orb in imp_flat],
    }

    result = {
        "mu": mu,
        "n_center": n_center,
        "n_imp_ground": n_ground,
        "e_ground": e_ground,
        "weight_fraction": weight_fraction,
        "num_states": num_states,
        "max_energy": max_energy,
        "tau": ctx.tau,
        "bandwidth": ctx.bandwidth,
        "states": {},
        "representability": {},
        "enumerated_weight": {},
        "sum_rule": sum_rule,
    }
    result.update(spectral_moments(h_op, psi_ground, e_ground, imp_flat))

    for n in (n_center + 1, n_center - 1):
        if sectors[n] is None:
            result["states"][n] = None
            continue
        es, psis, sector_basis = sectors[n]
        order = np.argsort(np.real(es))
        phis = seeds[n]
        seed_norm2 = sum(_norm2(phi) for phi in phis)
        result["representability"][n] = (
            None if seed_norm2 == 0 else sum(_supported_norm2(phi, sector_basis) for phi in phis) / seed_norm2
        )
        rows = []
        for rank_index, k in enumerate(order):
            psi = psis[k]
            rho = build_density_matrices(sector_basis, [psi], imp_flat, imp_flat)[0]
            weight = sum(abs(_overlap(psi, phi)) ** 2 for phi in phis)
            rows.append(
                {
                    "index": rank_index,
                    "energy": float(np.real(es[k])),
                    # The pole position on the omega axis: E_n[N+1] - E_0[N] for addition,
                    # E_0[N] - E_n[N-1] for removal, matching the record's omega_+- convention.
                    "omega": float(np.real(es[k])) - e_ground if n > n_center else e_ground - float(np.real(es[k])),
                    "n_imp": float(np.real(np.trace(rho))),
                    "delta": float(np.real(np.trace(rho))) - n_ground,
                    "weight": float(weight),
                    "norm2": _norm2(psi),
                }
            )
        total = sum(row["weight"] for row in rows)
        # Normalised against the **exact** sum rule, never against the enumerated total. The
        # enumeration is generically incomplete -- on the charge-transfer fixture the first 25
        # states hold 16% of the addition weight, because the impurity pole sits far above the
        # bath level the criterion fixes against -- and dividing by the enumerated total then
        # reports that bath level as carrying 93% of the addition weight when its true share is
        # 15%. A denominator that shrinks with the window turns "I did not look far enough" into
        # "this state is the edge", which is precisely the error under investigation.
        denominator = result["sum_rule"].get(n) or total
        cumulative = 0.0
        for row in rows:
            row["weight_fraction"] = 0.0 if denominator == 0 else row["weight"] / denominator
            cumulative += row["weight"]
            row["cumulative"] = cumulative
        result["states"][n] = rows
        result["enumerated_weight"][n] = total

    def _edges(n):
        rows = result["states"].get(n)
        if not rows:
            return None, None, None
        unweighted = rows[0]["omega"]
        weighted = next((row["omega"] for row in rows if row["weight_fraction"] >= weight_fraction), None)
        # Threshold-free companion: the first moment of the enumerated part of A_imp on this
        # side. It answers "where is this side's weight, on average" without anyone choosing a
        # cut, which is the one number in this table that cannot be argued with -- at the cost of
        # being a centre of gravity rather than an edge, and of inheriting whatever the
        # enumeration missed.
        total = sum(row["weight"] for row in rows)
        centroid = None if total == 0 else sum(row["weight"] * row["omega"] for row in rows) / total
        return unweighted, weighted, centroid

    result["omega_plus"], result["omega_plus_w"], result["omega_plus_centroid"] = _edges(n_center + 1)
    result["omega_minus"], result["omega_minus_w"], result["omega_minus_centroid"] = _edges(n_center - 1)
    result["centre"] = _centre(result["omega_plus"], result["omega_minus"])
    result["centre_w"] = _centre(result["omega_plus_w"], result["omega_minus_w"])
    result["centre_centroid"] = _centre(result["omega_plus_centroid"], result["omega_minus_centroid"])
    return result


def _centre(omega_plus, omega_minus):
    """``(omega_+ + omega_-)/2``, or ``None`` where either edge is undefined."""
    if omega_plus is None or omega_minus is None:
        return None
    return 0.5 * (omega_plus + omega_minus)


def format_table(result, e_scale=1.0, unit=""):
    """The per-state table as text, one block per sector."""
    lines = []
    mu, n_center = result["mu"], result["n_center"]
    lines.append(
        f"mu = {mu:+.6f}{unit}   n_center = {n_center}   <n_imp> = {result['n_imp_ground']:.4f}   "
        f"tau = {result['tau']:g}   states/sector <= {result['num_states']}   "
        f"weight cut = {result['weight_fraction']:.2f}"
    )
    for n in (n_center + 1, n_center - 1):
        rows = result["states"].get(n)
        label = "ADDITION  N+1" if n > n_center else "REMOVAL   N-1"
        if not rows:
            lines.append(f"  {label} (sector {n}): unreachable")
            continue
        rep = result["representability"].get(n)
        total, exact = result["enumerated_weight"].get(n), result["sum_rule"].get(n)
        lines.append(
            f"  {label} (sector {n}): representability = {rep:.4f}   "
            f"enumerated weight = {total:.4f} of {exact:.4f} ({total / exact:.1%})"
            if rep is not None and exact
            else f"  {label} (sector {n}):"
        )
        lines.append("      k   omega        delta      weight     frac    cum/exact")
        for row in rows:
            lines.append(
                f"    {row['index']:3d}   {row['omega'] * e_scale:+10.5f}  {row['delta']:+8.4f}  "
                f"{row['weight']:9.5f}  {row['weight_fraction']:6.3f}  "
                f"{(row['cumulative'] / exact if exact else float('nan')):8.3f}"
            )
    for key in (
        "omega_plus",
        "omega_plus_w",
        "omega_plus_centroid",
        "omega_minus",
        "omega_minus_w",
        "omega_minus_centroid",
        "centroid_plus",
        "centroid_minus",
        "centre",
        "centre_w",
        "centre_centroid",
        "centre_moment",
    ):
        value = result[key]
        lines.append(f"  {key:14s} = {'undefined' if value is None else f'{value * e_scale:+.6f}'}{unit}")
    return "\n".join(lines)


def main(argv=None):
    """``<workload> <cap> <mu>`` -- the invocation this module's docstring has always advertised.

    It did not exist. The module documented ``python -m impurityModel.test.support.dc_weights
    nio_5peeled 2000 -0.2587`` and had no ``__main__`` block, so that command **exited 0 and
    printed nothing** -- a silent no-op, which is worse than an error because it reads as "there
    was nothing to report". ``fixed_gap_dc``'s impurity-character warning now names this command as
    the way to tell a charge-transfer valence band from a bath-discretization artefact, so it has
    to run.

    ``mu`` is the trial shift in ``dc = dc_guess + mu``, in the archive's own energy unit (Ry for
    an RSPt archive), matching the record's ``mu``. The iteration is pinned rather than following
    the archive's last group: these archives are live, and the iterations of one run differ by
    several eV.
    """
    import argparse

    from impurityModel.ed.model import load_selfenergy_archive

    from .restriction_diagnostics import DEFAULT_ITERATION, WORKLOADS

    parser = argparse.ArgumentParser(description="Impurity spectral weight at the gap edges.")
    parser.add_argument("workload", choices=sorted(WORKLOADS), help="archive key")
    parser.add_argument("cap", type=int, help="determinant cap (truncation_threshold)")
    parser.add_argument("mu", type=float, help="trial DC shift, in the archive's energy unit")
    parser.add_argument("--iteration", type=int, default=DEFAULT_ITERATION)
    parser.add_argument("--num-states", type=int, default=DEFAULT_NUM_STATES)
    parser.add_argument("--weight-fraction", type=float, default=DEFAULT_WEIGHT_FRACTION)
    parser.add_argument("--verbosity", type=int, default=0)
    args = parser.parse_args(argv)

    model, _meshes, basis, solver, label = load_selfenergy_archive(WORKLOADS[args.workload], iteration=args.iteration)
    basis = replace(basis, truncation_threshold=args.cap)
    print(f"{args.workload} ({label}) iteration {args.iteration}, cap {args.cap}, mu {args.mu:+g}")
    result = sector_weight_table(
        model,
        basis,
        solver,
        args.mu,
        num_states=args.num_states,
        weight_fraction=args.weight_fraction,
        verbosity=args.verbosity,
    )
    print(format_table(result))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
